import type { Metadata } from "next";
import { Space_Mono } from "next/font/google";
import "./globals.css";

const spaceMonoRegular = Space_Mono({
  variable: "--font-space-mono-regular",
  weight: "400",
  subsets: ["latin"],
});

const spaceMonoBold = Space_Mono({
  variable: "--font-space-mono-bold",
  weight: "700",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceMonoRegular.variable} ${spaceMonoBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
